spring:
  # 配置数据库连接池
  datasource:
    url: jdbc:mysql://106.52.132.48:3306/basic_boot?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: just4fun
  ### 配置Redis
  redis:
    database: 0
    host: 10.0.0.32
    port: 6379
    password: 1470634109